platform :ios, '13'
use_modular_headers!

target 'BinanceChainKitExample' do
  pod 'HsToolKit.swift', git: 'https://github.com/baboaisystem/lib_hstool_swift'
  pod 'BinanceChainKit.swift', :path => '../'
  pod 'SnapKit'
end

target 'BinanceChainKitTests' do
  pod 'BinanceChainKit.swift', :path => '../'
end
